### ISSUE TITLE
Exclude .js extension

### ISSUE THREAD

**Issue by bjoerge** [andreypopp/reactify#30] opened 2014-11-24 11:09 UTC
We always use the `.jsx` extension for files with JSX syntax and don't want to run regular `.js` files through reactify. It would be nice to have the possibility to configure reactify to skip `.js` files.

This seems to be impossible currently as the `js` extension is included to no matter what the `options.extension` specifies here:
https://github.com/andreypopp/reactify/blob/0405176e95023f1ce2b475f39c9d52dd322a0564/index.js#L57

**Comment by mikecao** [comment] 2015-04-14 19:09
+1 I have a mix of `.js` and `.jsx` files as well and I don't want to run the transform at all for `.js` files. Maybe provide an `--only jsx` option.

**Comment by huang47** [comment] 2015-04-14 20:33
+1 on this, would be great if there is an option to opt out `.js` files

**Comment by huang47** [comment] 2015-04-16 02:40
how do you think we can do it in 2 phases to minimize the impact?

phase 1. 
for 1.x we can provide an opt-out in options so we can do
```browserify -t [ reactify --opt-out-extension js ] main.js``` without changing any current reactify semantics. And hence users won't run into any problems if they are using `^` in package.json
(that's set by default while doing `npm install reactify --save[-dev]`)
 
phase 2. 
transform jsx only and users have to opt-in `js` explicitly.
since it's a breaking change which said bumping version to 2.0.0 is necessary.

Any thoughts?

**Comment by mikecao** [comment] 2015-04-16 04:51
@huang47 I think the default should still be `js` and `jsx`, so people can just call reactify and it will work as it always has. The problem is that you can only add extensions to the defaults and not replace them because the code just concats them. We should just be able to replace the defaults with whatever extensions we want, like this:

`browserify -t [ reactify --extensions jsx,asx,bsx ] main.js`

**Comment by huang47** [comment] 2015-04-16 17:04
that's exactly why I suggest having 2 phases to introduce aforementioned changes
phase 1 only bump minor version which means `reactify` users do not worry about any changes.
phase 2 bump major version and users won't upgrade their dependencies accidentally (unless { "reactify": `"*"` } is used)

**Comment by mikecao** [comment] 2015-04-16 17:17
What I'm saying is that you don't need any phases, just a new parameter `--extensions` that uses whatever extensions are passed in. Existing users won't be affected at all.

**Comment by huang47** [comment] 2015-04-16 17:48
I was thinking that too but that makes the API / implementation really fragile

`--extension` opt-in additional ext whereas `--extensions` override built-in extensions and that can cause a nightmare to figure out which takes precedence.

**Comment by kurttheviking** [comment] 2015-04-26 17:02
hi all; we have a very large codebase (similar to others here) that we're migrating incrementally to react; I expected extensions to override the default -- but it seems it just extends them. that is a very surprising behavior as most browserify transforms provide a default that can be changed.

**Comment by mikecao** [comment] 2015-04-27 00:35
@kurttheviking There is a pull request sitting in the queue that does exactly that.

https://github.com/andreypopp/reactify/pull/63

**Comment by kurttheviking** [comment] 2015-04-28 05:33
:+1: I saw that; thank you!

**Comment by weepy** [comment] 2015-05-19 21:08
adding in the reactify transform makes my watchify speed crawl. Even secondary builds have moved to 4s from 0.4s. I'm not yet sure why, but it must be something to do with parsing everything

**Comment by moll** [comment] 2015-07-17 19:54
:+1:
Good for enforcing `.jsx` for JSX-y files and limiting the amount of work done for every other file.

**Comment by SimonFrr** [comment] 2015-09-17 17:58
I would love to have this. Anyone knows whether #63 or #69 are going to be merged someday soon?

**Comment by jasonmcaffee** [comment] 2016-01-08 00:47
+1 this is needed.
In the meantime, I came up with a simple workaround that drastically improved my build time (was 8.5 seconds and now is 2.5 seconds)
Wrap the reactify transform with your own transform, and apply any filtering logic you want.
In my case, I only want to use reactify for files with the .jsx extension.
For non-jsx files, I just provide a passthrough call to through.
You will need to add a dependency to "through2" in your package.json.

```javascript

var reactify = require('reactify');
var through = require('through2');

function customTransform(file, options){
    if(file.indexOf('.jsx') >= 0){
        return reactify(file, options);
    }else{
        return through(function(buf, enc, next){
            this.push(buf);
            next();
        })
    }
}
```

**Closed** 2016-06-02 08:48 UTC
